DO
$$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'qris_admin') THEN
    CREATE ROLE qris_admin LOGIN PASSWORD 'QrisAdmin_2026!';
  ELSE
    ALTER ROLE qris_admin WITH LOGIN PASSWORD 'QrisAdmin_2026!';
  END IF;
END
$$;

GRANT CONNECT ON DATABASE qris_dashboard TO qris_admin;

\connect qris_dashboard

GRANT USAGE ON SCHEMA public TO qris_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO qris_admin;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO qris_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO qris_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO qris_admin;
